### ISSUE TITLE
Label PRs with merge conflicts

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/vox-pupuli-tasks#1]
Proper management for our issues and pull requests is important. Automation can help us a lot. Our conecpt: There are pull requests where we need to act (review, merge) and where we wait for the contributor. github provides the `mergeable` attribute in the API. It allows us to check if there is a merge conflict or not. If there is a conflict, we need to add the label. If it gets rebased, we need to remove the label

```sh
curl -s https://api.github.com/repos/voxpupuli/puppet-keepalived/pulls/150 | jq .'mergeable' 
false
```

If desired, we could configure the application within the repositories, so github will deliver events to us (so we don't need to poll for this, which would be stupid).

---

The [GitHub API](https://developer.github.com/v3/issues/#edit-an-issue) allows us to update labels,

---

GitHub does not send out emails to collaborators if their pull request isn't mergeable nor when a label gets added. So in addition to the labels we should probably add an automatic comment to the PR?

**Comment by Flipez** [comment]
Implemented with https://github.com/voxpupuli/vox-pupuli-tasks/pull/35
