### ISSUE TITLE
App uses wrong context for github interactions

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/vox-pupuli-tasks#103]
We have two different GitHub contexts that we can use. The first one is our bot account: https://github.com/pccibot
The second one is the app itself. The app has administrator permissions. That allows it to add labels to a repository and also enables it to check if a group, for example our collaborators, have write access. The app currently does all GitHub interaction with the bot context. This is wrong and needs to be updated.

**Comment by Flipez** [comment]
Fixed
