### ISSUE TITLE
RepoStatusWorker: Ensure .sync.yml is valid

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/vox-pupuli-tasks#157]
a .sync.yml should at least have the following structure:

```yaml
---
.travis.yml:
  secure: "some base64 string"
```

We should check that it contains a nested hash with the keys `.travis.yml` and `secure`

**Comment by ekohl** [comment]
Note I also have written https://github.com/voxpupuli/modulesync_config/blob/master/bin/set-travis-secret to set these secrets based on plumbing.
