### ISSUE TITLE
Best ways to interact with GitHub

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/vox-pupuli-tasks#5]
There are three ways to interact with GitHub

## Webhooks

Hooks can be configured on a per-repo and per-org level. They will send notifications url-encoded or as json to a defined URL. Triggers can be configured for many things (new issues, PRs, releases, new comments...). This is the easiest way to integrate unidirectional applications.

## GitHub apps

configure many APIs to deliver data to this application. It will act on it's own. [Upstream docs](https://developer.github.com/apps/about-apps/#about-github-apps)

## OAuth apps

an OAuth application impersonates user actions. This is the desired type of application if you want to use GitHub for authentication and authorization (without any further action on github.com) and/or if you want to automate things for users (act on their behalf). [Upstream docs](https://developer.github.com/apps/about-apps/#about-oauth-apps). OAuth apps are always hosted somewhere by the user (doesn't this apply for GitHub apps?)

---

GitHub also [has a nice diagram](https://developer.github.com/apps/about-apps/#determining-which-integration-to-build) to help determining what kind of integrations fulfills all needs.

I think we need to decide if every actions happens on the behalf of a user or not. For automatic comments (like mentioned in https://github.com/Flipez/vox-pupuli-tasks/issues/1) it probably makes more sense to use a bot identity and don't act as a user.

**Comment by Flipez** [comment]
Switched to GitHub Apps long time ago
