### ISSUE TITLE
Explain each item

### ISSUE THREAD

**Issue by ghoneycutt** [voxpupuli/vox-pupuli-tasks#65]
There should be a way to explain each item. Such as `?` button or mouse over. Explaining what each check does as well as what can be done to remediate it would make it easier for people to contribute to fix those issues.

 For example, to figure out what `Supports Eol Ubuntu` means, I had to look at the code to see which versions are supported.

Instead it should look something like

We support Ubuntu versions 14.04, 16.04 and 18.04. Versions before 14.04 should not be supported since they are end of life (EOL). Check out this PR as an example. Besides modifying the `metadata.json` be sure to look through the README, data, nodesets, manifests, tests, etc....

**Comment by Flipez** [comment]
Hi @ghoneycutt,

I've added some descriptions.

![grafik](https://user-images.githubusercontent.com/1612489/65373923-2a996300-dc84-11e9-9f31-e6851d115b22.png)

Hope that helps!
