### ISSUE TITLE
operatingsystem_support wrongly used

### ISSUE THREAD

**Issue by Dan33l** [voxpupuli/vox-pupuli-tasks#82]
`Last sync was 2019-09-24 16:55:37 UTC` and `puppet-openvpn` is reported with missing `operatingsystem_support`.
But `metadata.json` of the module have this section:
https://github.com/voxpupuli/puppet-openvpn/blob/master/metadata.json#L11

**Comment by dhoppe** [comment]
I think this happens, because vox-pupuli-tasks is missing a list of releases. 
https://github.com/voxpupuli/vox-pupuli-tasks/blob/345a5fbe98827935e315fa57b36e436eac3e3ddc/app/workers/repo_status_worker.rb#L43-L82

**Comment by Flipez** [comment]
Hi @Dan33l 

You are missing `operatingsystemrelease` for FreeBDS: https://github.com/voxpupuli/puppet-openvpn/blob/master/metadata.json#L46

Therefore our logic raises this - not very helpful - error. If you fix this the error will disappear.

We will rework the whole logic of the RepoStatusWorker soon and will improve these errors and messages.

**Comment by Flipez** [comment]
I'll close this since the checks seem to work now better and do display the correct information (https://voxpupu.li/repositories/puppet-openvpn)
